server:
  port: 8083

spring:
  application:
    name: review-service

  config:
   import: optional:configserver:http://localhost:8888

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: chinu
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    sampling:
      probability: 1.0